In [2]:
import pandas as pd

In [3]:
# Load the data from the CSV file
file_path = 'water_potability_cleaned.csv'
df = pd.read_csv(file_path)

# Show the first few rows of the dataframe
df.head()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,7.036752,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,333.073546,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,333.073546,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0

In [4]:
from sklearn.model_selection import train_test_split

# Features (X) and Target (y) variables
X = df.drop("Potability", axis=1)
y = df["Potability"]

# Split the data into training and test sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shape of the resulting sets
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((2620, 9), (656, 9), (2620,), (656,))

In [ ]:
# Performing RFE

In [5]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Initialize a Random Forest Classifier
rf = RandomForestClassifier(random_state=42)

# Initialize RFE with the RandomForestClassifier model and desired number of features
# Here, I'll start with 1 to see which is the most important feature
rfe = RFE(rf, n_features_to_select=1)

# Fit RFE
rfe = rfe.fit(X_train, y_train)

# Display the ranking of features
feature_ranking = pd.DataFrame({'Feature': X_train.columns, 'Ranking': rfe.ranking_})
feature_ranking.sort_values(by='Ranking')

           Feature  Ranking
1         Hardness        1
2           Solids        2
3      Chloramines        3
0               ph        4
4          Sulfate        5
6   Organic_carbon        6
5     Conductivity        7
8        Turbidity        8
7  Trihalomethanes        9

In [6]:
# Initialize a dictionary to store accuracy scores for different feature subsets
accuracy_scores = {}

# Sort features by ranking
sorted_features = feature_ranking.sort_values(by='Ranking')['Feature'].values

# Loop through and find the accuracy for different feature subsets
for i in range(1, len(sorted_features) + 1):
    selected_features = sorted_features[:i]
    X_train_selected = X_train[selected_features]
    X_test_selected = X_test[selected_features]
    
    # Train the Random Forest Classifier on the selected features
    rf.fit(X_train_selected, y_train)
    
    # Make predictions and calculate accuracy
    y_pred = rf.predict(X_test_selected)
    accuracy = accuracy_score(y_test, y_pred)
    
    # Store the accuracy score
    accuracy_scores[i] = accuracy

# Display the accuracy scores for different feature subsets
accuracy_scores_df = pd.DataFrame(list(accuracy_scores.items()), columns=['Number of Features', 'Accuracy'])
accuracy_scores_df
# Reverse order

   Number of Features  Accuracy
0                   1  0.557927
1                   2  0.567073
2                   3  0.568598
3                   4  0.614329
4                   5  0.676829
5                   6  0.678354
6                   7  0.670732
7                   8  0.682927
8                   9  0.693598

In [ ]:
    # Hardness
    # Solids
    # Chloramines
    # ph
    # Sulfate
    # Organic_carbon